use std::path::PathBuf;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    /* BUGFIX: Use vendored C source (vendor/) instead of ../src/.
     * crates.io packages can't include files outside the crate directory,
     * so ../src/ doesn't work when published. The vendor/ directory
     * contains a copy of the C source, bundled with the crate. */
    let vortex_src = PathBuf::from(&manifest_dir).join("vendor");
    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    /* ---- Generate vortex_config.h from template ----
     *
     * The C source files #include "vortex_config.h", which is normally
     * generated by CMake from vortex_config.h.in. Since we don't depend
     * on CMake, we read the .in template, do the @VAR@ substitution
     * ourselves, and write the result to OUT_DIR. */
    let template = vortex_src.join("vortex_config.h.in");
    let generated_config = out_path.join("vortex_config.h");

    if template.exists() {
        let template_contents = std::fs::read_to_string(&template)
            .expect("Failed to read vortex_config.h.in");
        let config_contents = substitute_template(&template_contents);
        std::fs::write(&generated_config, config_contents)
            .expect("Failed to write vortex_config.h");
    } else {
        std::fs::write(&generated_config, generate_minimal_config())
            .expect("Failed to write vortex_config.h");
    }

    let mut c_files = Vec::new();
    collect_c_files(&vortex_src, &mut c_files);

    let mut cc_build = cc::Build::new();
    cc_build
        .compiler("gcc")
        .flag("-std=gnu17")
        .flag("-O3")
        .flag("-fPIC")
        .flag("-DNDEBUG")
        .flag("-Wno-unused-variable")
        .flag("-Wno-unused-function")
        .flag("-Wno-unused-but-set-variable")
        .flag("-Wno-unused-parameter")
        .flag("-Wno-sign-compare")
        .flag("-Wno-discarded-qualifiers")
        .flag("-Wno-incompatible-pointer-types");

    cc_build.include(&vortex_src);
    cc_build.include(&out_path);

    cc_build.define("NDEBUG", None);

    for f in &c_files {
        cc_build.file(f);
    }
    cc_build.compile("vortex");

    let wrapper = PathBuf::from(&manifest_dir).join("wrapper.h");

    #[cfg(feature = "bindgen")]
    {
        let clang_lib = PathBuf::from(std::env::var("LIBCLANG_PATH")
            .unwrap_or_else(|_| "/usr/lib".to_string()));
        let bindings = bindgen::Builder::default()
            .header(wrapper.to_str().unwrap())
            .clang_arg(format!("-I{}", vortex_src.display()))
            .clang_arg(format!("-I{}", out_path.display()))
            .clang_arg(format!("-isystem{}/lib/clang/15.0.0/include", clang_lib.display()))
            .clang_arg("-isystem/usr/lib/gcc/x86_64-linux-gnu/14/include")
            .clang_arg("-isystem/usr/include")
            .allowlist_type("vtx_.*")
            .allowlist_function("vtx_.*")
            .allowlist_var("VTX_.*")
            .allowlist_var("VORTEX_.*")
            .allowlist_var("VT_OP_.*")
            .allowlist_type("VT_OP_.*")
            .layout_tests(false)
            .generate_inline_functions(true)
            .generate()
            .expect("Failed to generate bindings (install libclang)");
        bindings.write_to_file(out_path.join("bindings.rs"))
            .expect("Failed to write bindings");
    }

    #[cfg(not(feature = "bindgen"))]
    {
        let pregen = PathBuf::from(&manifest_dir).join("src").join("bindings.rs");
        if pregen.exists() {
            std::fs::copy(&pregen, out_path.join("bindings.rs"))
                .expect("Failed to copy pre-generated bindings");
        } else {
            std::fs::write(out_path.join("bindings.rs"),
                "// No bindings available. Enable 'runtime-bindgen' feature.\n")
                .unwrap();
        }
    }

    for f in &c_files {
        println!("cargo:rerun-if-changed={}", f.display());
    }
    println!("cargo:rerun-if-changed={}", wrapper.display());
    println!("cargo:rerun-if-changed={}", generated_config.display());
    println!("cargo:rerun-if-changed={}", template.display());
}

fn substitute_template(template: &str) -> String {
    /* Substitute @VAR@ placeholders in vortex_config.h.in with default
     * values. #cmakedefine lines become #define (all features enabled). */
    let mut result = String::new();
    for line in template.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("#cmakedefine ") {
            let define = &trimmed["#cmakedefine ".len()..];
            result.push_str(&format!("#define {}\n", define));
        } else if trimmed.contains("@") {
            let substituted = replace_placeholders(line);
            result.push_str(&substituted);
            result.push('\n');
        } else {
            result.push_str(line);
            result.push('\n');
        }
    }
    result
}

fn replace_placeholders(line: &str) -> String {
    line.replace("@VORTEX_CACHE_MAX_SIZE@", "268435456")
        .replace("@VORTEX_T1_THRESHOLD@", "1000")
        .replace("@VORTEX_T2_THRESHOLD@", "10000")
        .replace("@VORTEX_COMPILE_THREADS@", "0")
}

fn generate_minimal_config() -> String {
    r#"#ifndef VORTEX_CONFIG_H
#define VORTEX_CONFIG_H

#define VORTEX_ENABLE_ASSERTIONS
#define VORTEX_ENABLE_VERIFY
#define VORTEX_ENABLE_PROFILING
#define VORTEX_ENABLE_SOTA

#define VORTEX_CACHE_MAX_SIZE 268435456
#define VORTEX_T1_THRESHOLD 1000
#define VORTEX_T2_THRESHOLD 10000
#define VORTEX_COMPILE_THREADS 0
#define VORTEX_T3_THRESHOLD (VORTEX_T2_THRESHOLD * 10)

#define VTX_TAG_BITS 3
#define VTX_TAG_MASK ((1ULL << VTX_TAG_BITS) - 1)
#define VTX_SMI_MAX ((1LL << 46) - 1)
#define VTX_SMI_MIN (-(1LL << 46))
#define VTX_POLY_LIMIT 4
#define VTX_PROFILE_TYPE_BUFFER_SIZE 32

#endif /* VORTEX_CONFIG_H */
"#.to_string()
}

fn collect_c_files(dir: &PathBuf, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_c_files(&path, files);
            } else if path.extension().and_then(|e| e.to_str()) == Some("c") {
                if path.file_name().and_then(|n| n.to_str()) != Some("main_new.c") {
                    files.push(path);
                }
            }
        }
    }
}
